### ISSUE TITLE
We're not following the SemVer principle

### ISSUE THREAD

**Issue by owzim** [processwire-recipes/Recipes#13]
* the first version of a recipe should really be 1.0.0
* if it undergoes a decent amount of changes (structural in code, or decent amount of text), it should be a `minor` version change, e.g. 1.1.0
* if there's a typo fix or a small code fix it should be `bug-fix` version change e.g. 1.1.1

We're not following this principle as of now.

**Comment by marcus-herrmann** [comment]
Right. Fortunately the directory is still quite small so we could change it globally without much work. Additionally, adding this info to the FAQ and contribute pages, as well as the author mention on 3rd-party-contributed recipes.

**Comment by marcus-herrmann** [comment]
Refactoring proposal pushed to master, but not yet imported to PWR via installer: https://github.com/processwire-recipes/Recipes/commit/dd01c262cc60e21c40543866225785a941c876d6 - please free to either correct or approve via import.

**Comment by owzim** [comment]
approved, imported, thanks for taking the time to do this.
