### ISSUE TITLE
Creating custom fields

### ISSUE THREAD

**Issue by owzim** [processwire-recipes/Recipes#18]
https://processwire.com/talk/topic/9186-creating-custom-fields/?p=88872

Perhaps too much for a recipe?

**Comment by marcus-herrmann** [comment]
Yeah, this (although showcasing ProcessWire's abilities) deserves a proper tutorial state, imho. I'd draw the line between recipe and tutorial as soon as it comes to module creation, which opens a new context and requiring further explanation.

**Comment by owzim** [comment]
I see. Agreed.
