### ISSUE TITLE
Changing the default language 

### ISSUE THREAD

**Issue by owzim** [processwire-recipes/Recipes#19]
https://processwire.com/talk/topic/9322-change-default-language-for-homepage/?p=89717

**Comment by marcus-herrmann** [comment]
Thanks for the link, but I tend to draw the line between recipe and not-recipe at the edge of modules - as far as I can see this can be and was wrapped into module form.

But please feel free to differ.

**Comment by owzim** [comment]
I think of recipes as snippets you can just copy, paste and modify to your liking, regardless of where you put them. 

If we limit them to say `config.php` and templates, a lot of cool stuff would be left out, because in the long run every PW dev will eventually use `modules` for customization, and I think it should be the preferred way instead of cluttering your templates and other places with logic. To set a good example ...

**Comment by marcus-herrmann** [comment]
Right. I'd like to draw set line now for modules that are in the official directory now ('cause installing them via PW interface would be easier as the easiest recipe, and I don't see PWR as a module recommendation hub). Thoughts?

On another note: I definitely have to convert some of the candidates collected here to proper recipes...

**Comment by owzim** [comment]
What I meant was, also allowing recipes to be mini modules. So they can be saved in the modules directory and installed. Misunderstanding?

Regarding candidates, I am not adding them, expecting you to get them into recipe shape and add them. I am doing that so they can be discussed, either disregarded or accepted and further down, we can decide who will add them, via assigning each issue to one of us.

**Comment by marcus-herrmann** [comment]
No misunderstanding. Let's just try it the way you suggest. I must not be too picky after all in this early phase of the project ;)

@Candidates: No, didn't understand it that way either. Was refering to me agreeing you on eligibility of some candidates.
